# syntax=docker/dockerfile:1


FROM rust:1.58.1-slim-buster as builder

WORKDIR /usr/src/naivecoin
COPY . /usr/src/naivecoin/

RUN cargo install --path .

FROM debian:buster-slim

COPY --from=builder /usr/local/cargo/bin/naivecoin /usr/local/bin/naivecoin

CMD ["naivecoin"]