name: CI
on:
  push:
    branches:
      - '*'
jobs:
  test-sockets:
    name: Test sockets
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: '**/sockets/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/sockets/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        env:
          cache-name: cache-node-modules

      - name: Install node modules
        run: |
          cd sockets
          yarn

      - name: Test
        run: |
          cd sockets
          yarn test

  test-core:
    name: Test Core
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: '**/core/target'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/core/Cargo.lock') }}
        env:
          cache-name: cache-rust-target

      - name: Test
        run: |
          cd core
          cargo test
