name: CI
on:
  push:
    branches:
      - '*'
jobs:
  test-sockets:
    name: Test sockets
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node modules
        run: |
          cd sockets
          yarn

      - name: Test
        run: |
          cd sockets
          yarn test

  test-core:
    name: Test Core
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd core
          cargo
